### ISSUE TITLE
**Mgr クラスの廃止

### ISSUE THREAD

**Issue by rz7d** [underecho/MTwit#9]
可読性を上げるために **Mgr クラスを廃止してください。

- ~~TwitterMgr~~https://github.com/stilllogic20/MTwit/commit/38093477fe42ba21ff9f8869a33f427fed0aeb7e
- ~~WindowMgr~~ https://github.com/stilllogic20/MTwit/commit/e3759a8d54704be28dbe7f407594b27d9236e66c

これらのクラスには複数の機能が含まれており、保守性が低下しています。
機能を適切に分割してより使いやすくすることで、可読性を向上させます。

**Comment by underecho** [comment]
Already fixed by https://github.com/stilllogic20/MTwit/commit/38093477fe42ba21ff9f8869a33f427fed0aeb7e
